///////////////////////////////////////////////////////////
//  Bouteille.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      06-févr.-2025 11:09:02
//  Original author: LDasylva
///////////////////////////////////////////////////////////




public class Bouteille {

	private readonly double capaciteEnLitre;
	private double contenaceEnLitre;
	private bool estOuverte;

	public Bouteille(){

	}

	~Bouteille(){

	}

	public virtual void Dispose(){

	}

	public bool Fermer(){

		return false;
	}

	public bool Ouvrir(){

		return false;
	}

	/// 
	/// <param name="quantiteEnLitre"></param>
	public bool Remplir(double quantiteEnLitre){

		return false;
	}

	public bool RemplirTout(){

		return false;
	}

	/// 
	/// <param name="quantiteEnLitre"></param>
	public void Vider(double quantiteEnLitre){

	}

	public bool ViderTout(){

		return false;
	}

	public bouteille(){

	}

	/// 
	/// <param name="estOuverte"></param>
	/// <param name="contenanceEnLitre"></param>
	/// <param name="capaciteEnLitre"></param>
	public bouteille(bool estOuverte, double contenanceEnLitre, double capaciteEnLitre){

	}

}//end Bouteille