DROP DATABASE IF EXISTS emp;

CREATE DATABASE IF NOT EXISTS emp;

use emp;

CREATE TABLE departements
(
DEPTNO INT PRIMARY KEY,
DNAME VARCHAR(100) NOT NULL , 
LOC VARCHAR(100) NOT NULL
);

CREATE TABLE employes
(
EMPNO INT PRIMARY KEY,
ENAME VARCHAR (100) NOT NULL,
JOB VARCHAR (100) NOT NULL,
MGR INT ,
HIREDATE DATE NOT NULL,
SAL INT NOT NULL,
COMM INT,
DEPTNO INT,
FOREIGN KEY (DEPTNO) REFERENCES departements(DEPTNO)
);

